# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: quay.io/droidian/build-essential:bookworm-amd64

stages:          # List of stages for jobs, and their order of execution
  - build

before_script:
  - apt update
  - apt install -y linux-packaging-snippets git
  - git checkout droidian
  - mkdir buildd
  
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - debian/rules debian/control
    - BRANCH=$(git rev-parse --abbrev-ref HEAD)
    - COMMIT=$(git rev-parse HEAD)
    - COMMENT="${BRANCH}"
    - RELENG_HOST_ARCH="arm64"
    - ARGS="--commit ${COMMIT} --comment ${COMMENT} --branch ${BRANCH}"
    - releng-build-changelog $ARGS
    - package_info=$(head -n 1 debian/changelog)
    - package_name=$(echo "${package_info}" | awk '{ print $1 }')
    - mk-build-deps --remove --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes" debian/control
    - rm -f ${package_name}-build-deps_*.*
    - ARGS="--no-lintian -d -sa --no-sign --jobs=$(nproc) --build=any"
    - ARGS="${ARGS} -a${RELENG_HOST_ARCH}"
    - eval debuild "${ARGS}"
    - cp out/KERNEL_OBJ/*.img buildd
    - cd ..
    - cp *.deb kernel_motorola_sm6125/buildd/

# The files which are to be made available in GitLab
  artifacts:
    paths:
      - buildd/*.deb
      - buildd/*.img

